### ISSUE TITLE
some suggestions for web development tools/best practices

### ISSUE THREAD

**Issue by jhpoelen** [mammaldiversity/mammaldiversity.github.io#3]
@liphardt @n8upham in a recent discussion, I promised to share some links to software/web development resources . 

1. continuous integration/unit testing - to help avoid bugs and drive modular design, I write unit tests and run them automatically in travis-ci.org every time I change any code or periodically. Most languages have unit testing framework. A test framework in node/javascript I use is Tape https://www.npmjs.com/package/tape . The neat thing is that Tape can also help test code that runs in a browser. For a more general background in unit testing and test driven development, please refer to standard text https://www.goodreads.com/book/show/387190.Test_Driven_Development . 

2. re-use existing libraries via package managers - to re-use existing libraries, package managers can be used to easily import and leverage code. Most languages have package managers. For node/javascript npm is a popular one. For client-side (in browser) javascript, I'd highly recommend using a package manager in combination with something like browserify https://en.wikipedia.org/wiki/Browserify  or similar to help package your javascript modules for use in a browser. 

3. keep it simple - you'll find that there's intimidating amount of (javascript) libraries / frameworks that help to make things "easier". Similarly, there's many very cool nosql databases, webservices, compile-to-javascript languages (e.g., coffeescript, typescript), infrastructures, platform-as-a service stuff out there that (cl)aim to make your life easier. However, I'd argue that most web application can do very well with static (optionally data driven/generated via Jekyll or Hugo) webpages with plain old css, html, javascript using standard web browser apis. I find the Mozilla Developer Network (MDN) documentation to be useful to learn more about the powerful capacities built into the browsers we use every day. https://developer.mozilla.org/en-US/ . 

Hope this helps and curious to hear comments.

**Comment by liphardt** [comment]
Thank you for the resources and advice @jhpoelen. 

My understanding of the motivation for revamping the site is to do exactly as you say and keep it as simple as possible so that it is maintainable into the future as others work on it. So I think doing our best to stick the html, css, and javascript to create a streamlined and static site is a good idea. 

Man, there are a lot of libraries out there and it is very intimidating. Right now I am trying to figure out how to structure the site so that everything will work correctly. You had mentioned that you think keeping the database just as a csv is the easiest thing to maintain in to the future so I am figuring out how to search it. There is csv parse on npm and then papa parse seems fairly popular. If I can figure out how to integrate the parsers to populate fields (like an infographic when hovering or something) on the fly using javascript instead of having each species given their own dedicated page I think that will make it easier to keep everything simple and maintainable moving forward. That way the actual csv can change as much as it wants and be updated without having to generate or change a bunch of pages. But I could be wrong with my thinking there. 

Thanks again for the resources.

**Comment by jhpoelen** [comment]
@liphardt great to hear that you are looking around for existing libraries to implement a basic search. 

One thing to keep in mind is that a web page with statically inserted taxonomic information can be searched using selectors, effectively turning a webpage into a searchable dynamic document/database.

So, if you embed the taxonomic information tag attributes (e.g., ```<div class="Animalia Mammalia Homo sapiens">```), you can use the https://developer.mozilla.org/en-US/docs/Web/API/Element/querySelector with javascript or css selectors to implement some fancy looking show/hide/search behavior.

Luckily you probably won't be the first to implement this behavior, because html/css/javascript/dom are widely used. 

Good luck with the search and implementation! I am curious to see what you'll come up with.

**Comment by n8upham** [comment]
Thanks @jhpoelen and @liphardt for the comments here -- I'm on board with everything you both have written here.  Schuyler demo'ed today some of the code he has been playing with and it looks good: fast, in browser searching using html tags, and starting to consider some javascript options.  My only feedback for now is to push & commit those changes more regularly, so that Jorrit can give feedback if / when appropriate.  Thanks both!
